"""empty message

Revision ID: c6af1954c34c
Revises: edbf18f21df5
Create Date: 2023-12-14 18:53:20.915996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6af1954c34c'
down_revision = 'edbf18f21df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_item_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['id'], ['id'])
        batch_op.drop_column('item')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_constraint('starships_item_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['id'], ['id'])
        batch_op.drop_column('item')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('starships_item_fkey', 'items', ['item'], ['id'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('characters_item_fkey', 'items', ['item'], ['id'])

    # ### end Alembic commands ###
