"""empty message

Revision ID: d16f5d9174bf
Revises: 6c61798168d5
Create Date: 2023-12-14 17:23:56.911263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16f5d9174bf'
down_revision = '6c61798168d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_img_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint('items_img_key', ['img'])

    # ### end Alembic commands ###
