"""empty message

Revision ID: edbf18f21df5
Revises: d16f5d9174bf
Create Date: 2023-12-14 18:51:44.396445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbf18f21df5'
down_revision = 'd16f5d9174bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_item_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['id'], ['id'])
        batch_op.drop_column('item')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planets_item_fkey', 'items', ['item'], ['id'])

    # ### end Alembic commands ###
